import { Product } from "./types";

// Dados de exemplo. Na Fase 2, isso será substituído por consultas
// reais ao Supabase (tabela `products` + `product_variants`).
export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "charizard-vmax-darkness-ablaze",
    name: "Charizard VMAX",
    game: "pokemon",
    subcategory: "cartas-avulsas",
    setName: "Darkness Ablaze",
    priceCents: 35000,
    condition: "NM",
    origin: "US",
    stock: 3,
    featured: true,
    description:
      "Carta avulsa Charizard VMAX, edição Darkness Ablaze, importada, em excelente estado de conservação.",
  },
  {
    id: "2",
    slug: "black-lotus-alpha",
    name: "Black Lotus",
    game: "magic",
    subcategory: "cartas-graduadas",
    setName: "Alpha",
    priceCents: 1200000,
    condition: "Graduada",
    origin: "US",
    stock: 1,
    featured: true,
    description:
      "Black Lotus, edição Alpha, peça rara para colecionadores, avaliada e graduada.",
  },
  {
    id: "3",
    slug: "blue-eyes-white-dragon-lob",
    name: "Blue-Eyes White Dragon",
    game: "yugioh",
    subcategory: "cartas-avulsas",
    setName: "Legend of Blue Eyes",
    priceCents: 28000,
    condition: "NM",
    origin: "US",
    stock: 5,
    featured: true,
    description: "Carta clássica Blue-Eyes White Dragon, edição Legend of Blue Eyes.",
  },
  {
    id: "4",
    slug: "booster-box-scarlet-violet",
    name: "Booster box Scarlet & Violet",
    game: "pokemon",
    subcategory: "produtos-selados",
    setName: "Scarlet & Violet",
    priceCents: 62000,
    compareAtPriceCents: 68000,
    condition: "Novo",
    origin: "BR",
    stock: 8,
    featured: true,
    description: "Caixa lacrada com 36 pacotes de boosters, versão nacional.",
  },
  {
    id: "5",
    slug: "case-12-blisters-evolucoes-prismaticas",
    name: "Case de 12 blisters Evoluções Prismáticas",
    game: "pokemon",
    subcategory: "produtos-selados",
    setName: "Evoluções Prismáticas",
    priceCents: 43744,
    condition: "Novo",
    origin: "BR",
    stock: 4,
    description: "Case fechado com 12 unidades de blister, versão nacional lacrada.",
  },
  {
    id: "6",
    slug: "mini-lata-pikachu",
    name: "Mini lata colecionável Pikachu",
    game: "pokemon",
    subcategory: "colecionaveis",
    setName: "Coleção especial",
    priceCents: 35000,
    condition: "Novo",
    origin: "US",
    stock: 6,
    description: "Lata colecionável importada com boosters e peça exclusiva.",
  },
  {
    id: "7",
    slug: "kit-colecionavel-pikachu",
    name: "Kit colecionável Pikachu",
    game: "pokemon",
    subcategory: "colecionaveis",
    setName: "Coleção especial",
    priceCents: 68000,
    condition: "Novo",
    origin: "US",
    stock: 2,
    description: "Kit com pin exclusivo, boosters e carta promocional.",
  },
  {
    id: "8",
    slug: "revised-dual-land-underground-sea",
    name: "Underground Sea",
    game: "magic",
    subcategory: "produtos-antigos-raros",
    setName: "Revised",
    priceCents: 185000,
    condition: "SP",
    origin: "US",
    stock: 1,
    description: "Dual land clássica, edição Revised, peça de valor para colecionadores.",
  },
  {
    id: "9",
    slug: "codigo-pokemon-tcg-live-pack",
    name: "Código Pokémon TCG Live - pacote de boosters",
    game: "pokemon",
    subcategory: "codigos-digitais",
    setName: "Digital",
    priceCents: 1200,
    condition: "Novo",
    origin: "BR",
    stock: 50,
    description: "Código digital para resgate de boosters no aplicativo Pokémon TCG Live.",
  },
  {
    id: "10",
    slug: "luffy-op01-alt-art",
    name: "Monkey D. Luffy (alt art)",
    game: "one-piece",
    subcategory: "cartas-avulsas",
    setName: "Romance Dawn (OP-01)",
    priceCents: 95000,
    condition: "NM",
    origin: "JP",
    stock: 2,
    description: "Carta alternativa de Luffy, importada do Japão, primeira edição.",
  },
  {
    id: "11",
    slug: "elsa-cold-fire-lorcana",
    name: "Elsa - Fogo Gélido",
    game: "lorcana",
    subcategory: "cartas-avulsas",
    setName: "The First Chapter",
    priceCents: 42000,
    condition: "NM",
    origin: "US",
    stock: 3,
    description: "Carta rara Elsa da coleção de estreia de Disney Lorcana.",
  },
  {
    id: "12",
    slug: "mini-lata-eevee",
    name: "Mini lata colecionável Eevee",
    game: "pokemon",
    subcategory: "colecionaveis",
    setName: "Coleção especial",
    priceCents: 35000,
    condition: "Novo",
    origin: "US",
    stock: 6,
    description: "Lata colecionável importada com boosters e peça exclusiva.",
  },
];

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.featured);
}

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function formatPriceBRL(cents: number) {
  return (cents / 100).toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
  });
}
